<%
    layout("/templates/inc/layout.html"){
        include("uRUniversity_app.js"){}
        include("uRUniversity_logic.js"){}
        include("uRUniversity_layout.js"){}
        include("uRUniversity_form.js"){}
        include("uRUniversity_import.js"){}
    }
%>