<%
    layout("/templates/inc/layout.html"){
        include("uRAffiliatedWith_app.js"){}
        include("uRAffiliatedWith_logic.js"){}
        include("uRAffiliatedWith_layout.js"){}
        include("uRAffiliatedWith_form.js"){}
        include("uRAffiliatedWith_import.js"){}
    }
%>