<%
    layout("/templates/inc/layout.html"){
        include("srPostTopic_app.js"){}
        include("srPostTopic_logic.js"){}
        include("srPostTopic_layout.js"){}
        include("srPostTopic_form.js"){}
        include("srPostTopic_import.js"){}
    }
%>