<%
    layout("/templates/inc/layout.html"){
        include("srNewsResult_app.js"){}
        include("srNewsResult_logic.js"){}
        include("srNewsResult_layout.js"){}
        include("srNewsResult_form.js"){}
        include("srNewsResult_import.js"){}
    }
%>